indusis/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
    url(r'^admin/clientes/', include('clientes.urls')),
    url(r'^admin/proveedores/', include('proveedores.urls')),
    url(r'^admin/funcionarios/', include('funcionarios.urls')),
    url(r'^admin/ingredientes/', include('ingredientes.urls')),
    url(r'^admin/recetas/', include('recetas.urls')),
    url(r'^admin/ordenes/', include('ordenes.urls')),


    url(r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Change admin site title
admin.site.site_header = "GRAFI EXPRESS"
admin.site.site_title = "Industria grafica"

ordenes/urls.py
from django.conf.urls import patterns, include, url
from ordenes.autocomplete import *
from ordenes.views import *
from ordenes.ajax import *

urlpatterns = [
    

    url(r'^orden/(?P<pk>\d+)/detail/$', OrdenDetailView.as_view(), name='orden_det'),
    url(r'^orden/$', OrdenListView.as_view(), name='orden_lis'),

    url(r'^$', ordenes_presentacion),
]

ordenes/models.py
from django.db import models
from datetime import date

# Create your models here.
PENDIENTE=0
PROCESADO=1
ENTREGADO=2
ESTADOS_ORDENES=(
    (PENDIENTE,'Pendiente'),
    (PROCESADO,'Procesado'),
    (ENTREGADO,'Entregado')
)

class Orden(models.Model):
    class Meta:
        verbose_name = "Orden"
        verbose_name_plural = "Ordenes"

    cliente = models.ForeignKey('clientes.Cliente')
    fecha = models.DateField(default=date.today)
    estado = models.IntegerField(default=PENDIENTE, choices=ESTADOS_ORDENES, editable=False)
    total = models.DecimalField(max_digits=15, decimal_places=2)

    def __unicode__(self):
        return unicode("Orden Nro.: " + str(self.id))


class DetalleDeOrden(models.Model):
    class Meta:
        verbose_name = "Detalle de la orden"
        verbose_name_plural = "Detalle de la orden"

    orden = models.ForeignKey(Orden)
    receta = models.ForeignKey('recetas.Receta')
    cantidad = models.DecimalField(max_digits=15, decimal_places=2)
    precio_unitario = models.DecimalField(max_digits=15, decimal_places=2)
    subtotal = models.DecimalField(max_digits=15, decimal_places=2)

    def get_subtotal(self):
        return (self.cantidad*self.get_precio_unitario())

ordenes/forms.py
from dal import autocomplete
from django import forms
from recetas.models import *
from ordenes.models import *


class OrdenForm(forms.ModelForm):
	class Meta:
		model = Orden
		fields = ('__all__')
		widgets = { 
			"cliente": autocomplete.ModelSelect2(url='cliente-autocomplete'),
			"total":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
		}

	def __init__(self, *args, **kwargs):
		super(OrdenForm, self).__init__(*args, **kwargs)
		self.fields['total'].widget.attrs['readonly'] = True

class DetalleDeOrdenForm(forms.ModelForm):
	class Meta:
		model = DetalleDeOrden
		fields = ('__all__')
		widgets = {
			"cantidad":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
			"precio_unitario":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
			"subtotal":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
		}

	# para eliminar los popup edit y add
	receta = forms.ModelChoiceField(
		queryset=Receta.objects.all(),
		widget=autocomplete.ModelSelect2(url='receta-autocomplete'),
		required=True,
		label="RECETA"
	)

ordenes/views.py
from django.shortcuts import render, render_to_response
from django.template.context import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from django.db.models import Q

from clientes.models import *
from ordenes.models import *
from extra.globals import *

# Create your views here.
class OrdenListView(ListView):
    model = Orden
    template_name = "orden_list.html"
    paginate_by = 30

    def get_queryset(self):
        ordenes = Orden.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            ordenes = ordenes.filter( id__istartswith=q )

        cliente_id = self.request.GET.get('cliente_id', '')
        if cliente_id != '':
            ordenes = ordenes.filter(cliente_id=cliente_id)

        estado = self.request.GET.get('estado', '0')
        if estado != 'TODO':
            ordenes = ordenes.filter(estado=estado)

        fecha = self.request.GET.get('fecha', '')
        if fecha != '':
            vector = fecha.split("/")
            fecha = vector[2] + "-" + vector[1] + "-" + vector[0]
            ordenes = ordenes.filter(fecha=fecha)


        return ordenes.order_by("-id")

    def get_context_data(self, **kwargs):
        context = super(OrdenListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        context['clientes'] = Cliente.objects.all()
        context['cliente_id'] = int(self.request.GET.get('cliente_id', '')) if (self.request.GET.get('cliente_id', '') != '') else ''
        context['estado'] = self.request.GET.get('estado','0')
        context['fecha'] = self.request.GET.get('fecha','')
        return context

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(OrdenListView, self).dispatch(*args, **kwargs)

class OrdenDetailView(DetailView):
    model = Orden
    template_name = "orden_detail.html"

    def get_context_data(self, **kwargs):
        context = super(OrdenDetailView, self).get_context_data(**kwargs)
        context['detalles'] = DetalleDeOrden.objects.filter(orden_id=self.object.id)
        return context

def ordenes_presentacion(request):
    context = RequestContext(request)
    titulo="ORDENES"
    descripcion=".."
    return render_to_response('admin/presentacion.html', {'titulo': titulo, 'descripcion': descripcion}, context)

ordenes/templates/orden_detail.html
{% extends "admin/base_site.html" %}
{% load humanize %}

{% block content %}
<h1>Datos de la Orden</h1>
<table class="table table-striped table-filter" summary="Datos de la Orden.">
	<tbody>
		<tr>
			<th scope="row"> Numero </th>
			<td> {{ object.id }} </td>
		</tr>

		<tr>
			<th scope="row"> Cliente </th>
			<td> {{ object.cliente }} </td>
		</tr>

		<tr>
			<th scope="row"> fecha </th>
			<td> {{ object.fecha }} </td>
		</tr>

		<tr>
			<th scope="row"> estado </th>
			<td> {{ object.get_estado_display }} </td>
		</tr>

		<tr>
			<th scope="row"> Total </th>
			<td> {{ object.total|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }} </td>
		</tr>

	</tbody>
</table>

{% if detalles %}
<table id="result_list" class="table table-striped table-bordered table-hover table-condensed">
	<caption><h1>Detalle</h1></caption>

	<thead>
		<tr>
			<th>Receta</th>
			<th>Cantidad</th>
			<th>Precio unitario</th>
			<th>Subtotal</th>
		</tr>
	</thead>

	<tbody>
		{% for detalle in detalles %}
		<tr>
			<td>{{ detalle.receta }}</td>
			<td>{{ detalle.cantidad|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
			<td>{{ detalle.precio_unitario|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
			<td>{{ detalle.subtotal|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
		</tr>
		{% endfor %}
	</tbody>

</table>
{% endif %}

<button type="button" class="btn btn-primary" onclick="window.history.back(); return false;">Volver</button>

{% endblock %}

ordenes/templates/orden_list.html
{% extends 'admin/base_site.html' %}
{% load humanize %}

{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.maskedinput.min.js' %}"></script>
    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
    <script>
        jQuery(function($) {
            $(".date").mask("99/99/9999",{placeholder:"dd/mm/aaaa"});
        });
    </script>
{% endblock %}

{% block content %}
    <form class="form" method="get">
        <h1>Lista de Ordenes</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Numero:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text" class="search-query" placeholder="Numero.." name="q" value="{{ q }}">
                        </td>


                        <th style="vertical-align:middle">
                            <strong> Cliente:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select class="chosen-select" data-placeholder="Seleccione un cliente.." name="cliente_id" value="{{ cliente_id }}" onchange="this.form.submit();">
                                <option value=""></option>
                                {% for cliente in clientes %}
                                    <option {% if cliente.pk == cliente_id %} selected {% endif %} value="{{ cliente.id }}">{{ cliente }}</option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Estado:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select name="estado" value="{{ estado }}" onchange="this.form.submit();">
                                <option {% if '0' in estado %} selected {% endif %} value="0">Pendiente</option>
                                <option {% if '1' in estado %} selected {% endif %} value="1">Procesado</option>
                                <option {% if '2' in estado %} selected {% endif %} value="2">Entregado</option>
                                <option {% if 'TODO' in estado %} selected {% endif %} value="TODO">Todos</option>
                            </select>
                        </td>


                        <th style="vertical-align:middle">
                            <strong> Fecha:</strong>  
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text" class="date" placeholder="dd/mm/aaaa" name="fecha" value="{{ fecha }}">
                        </td>



                        <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                            <a class="btn btn-info" href="/admin/ordenes/orden" title="Limpiar Filtros">
                                <i class="fa fa-undo"></i>
                            </a>
                            <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                        </th>
                    </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">
            <!--
            <button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
                <i class="fa fa-file-excel-o"></i>
            </button>
            -->

            {% if perms.ordenes.add_orden %}
                <button type="button" class="btn btn-primary" onclick="location.href='/admin/ordenes/orden/add/';" title="Agregar Orden">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            {% endif %}

        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>
                <th>Numero</th>
                <th>Cliente</th>
                <th>Fecha</th>
                <th>Estado</th>
                <th>Total</th>                
                <th>Acciones</th>

            </tr>
            </thead>

            <tbody>
            {% for orden in object_list %}
                <tr>
                    <td>{{ orden.id }}</td>
                    <td>{{ orden.cliente }}</td>
                    <td>{{ orden.fecha }}</td>
                    <td>{{ orden.get_estado_display }}</td>
                    <td>{{ orden.total|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>

                    <td>
                        {% if perms.ordenes.change_orden %}
                            <button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/ordenes/orden/{{ orden.id }}/';" title="Editar">
                                <i class="fa fa-pencil"></i>
                            </button>
                        {% endif %}

                        {% if perms.ordenes.delete_orden %}
                            <button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/ordenes/orden/{{ orden.id }}/delete/';" title="Borrar">
                                <i class="fa fa-minus"></i>
                            </button>
                        {% endif %}


                        <button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/ordenes/orden/{{ orden.id }}/detail/';" title="Detalle">
                            <i class="fa fa-list-ol"></i>
                        </button>

                        <!--
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/ordenes/orden/{{ orden.id }}/print/';" title="Imprimir">
							<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
						</button>
						-->

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/ordenes/orden/?page={{ page_obj.previous_page_number }}&q={{ q }}&cliente_id={{ cliente_id }}&estado={{ estado }}&fecha={{ fecha }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/ordenes/orden/?page={{ page_obj.previous_page_number }}&q={{ q }}&cliente_id={{ cliente_id }}&estado={{ estado }}&fecha={{ fecha }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/ordenes/orden/?page={{ page }}&q={{ q }}&cliente_id={{ cliente_id }}&estado={{ estado }}&fecha={{ fecha }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/ordenes/orden/?page={{ page_obj.next_page_number }}&q={{ q }}&cliente_id={{ cliente_id }}&estado={{ estado }}&fecha={{ fecha }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/ordenes/orden/?page={{ page_obj.paginator.num_pages}}&q={{ q }}&cliente_id={{ cliente_id }}&estado={{ estado }}&fecha={{ fecha }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}