funcionarios/urls.py
from django.conf.urls import patterns, include, url
from funcionarios.autocomplete import *
from funcionarios.views import *

urlpatterns = [
    url(
        'funcionarioautocomplete/$',
        FuncionarioAutocomplete.as_view(),
        name='funcionario-autocomplete',
    ),

	url(r'^funcionario/(?P<pk>\d+)/detail/$', FuncionarioDetailView.as_view(), name='funcionario_det'),
	url(r'^funcionario/$', FuncionarioListView.as_view(), name='funcionario_lis'),

    url(r'^$', funcionarios_presentacion),
]

indusis/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
    url(r'^admin/clientes/', include('clientes.urls')),
    url(r'^admin/proveedores/', include('proveedores.urls')),
    url(r'^admin/funcionarios/', include('funcionarios.urls')),
    url(r'^admin/ingredientes/', include('ingredientes.urls')),
    url(r'^admin/recetas/', include('recetas.urls')),
    url(r'^admin/ordenes/', include('ordenes.urls')),


    url(r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Change admin site title
admin.site.site_header = "GRAFI EXPRESS"
admin.site.site_title = "Industria grafica"

funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User


class Funcionario(models.Model):
	nombres = models.CharField(max_length=100)
	apellidos = models.CharField(max_length=100)
	ruc = models.CharField(max_length=20, null=True, blank=True, verbose_name="RUC/CI Nro.")
	direccion = models.CharField(max_length=200, null=True, blank=True)
	email = models.EmailField(max_length=100, null=True, blank=True)
	fecha_de_ingreso = models.DateField(null=True, blank=True)
	observaciones = models.TextField(max_length=500, null=True, blank=True)
	usuario = models.OneToOneField(User, null=True, blank=True)
	
	def get_full_name(self):
		return self.nombres + " " + self.apellidos

	def __unicode__(self):
		return unicode(self.get_full_name())

funcionarios/views.py
from django.shortcuts import render, render_to_response
from django.template.context import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.db.models import Q
from funcionarios.models import Funcionario


class FuncionarioListView(ListView):
    model = Funcionario
    template_name = "funcionario_list.html"

    def get_queryset(self):
        funcionarios = Funcionario.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            funcionarios = funcionarios.filter( Q(nombres__icontains=q) | Q(apellidos__icontains=q) )

        return funcionarios


    def get_context_data(self, **kwargs):
        context = super(FuncionarioListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context

class FuncionarioDetailView(DetailView):
    model = Funcionario
    template_name = "funcionario_detail.html"

def funcionarios_presentacion(request):
    context = RequestContext(request)
    titulo="FUNCIONARIOS"
    descripcion=".."
    return render_to_response('admin/presentacion.html', {'titulo': titulo, 'descripcion': descripcion}, context)

funcionarios/templates/funcionario_detail.html
{% extends "admin/base_site.html" %}
{% load humanize %}

{% block content %}
<h1>Datos del Funcionario</h1>
<table class="table table-striped table-filter" summary="Datos del Funcionario.">
	<tbody>
		<tr>
			<th scope="row"> Nombres </th>
			<td> {{ object.nombres }} </td>
		</tr>
		<tr>
			<th scope="row"> Apellidos </th>
			<td> {{ object.apellidos }} </td>
		</tr>

		<tr>
			<th scope="row"> E-mail </th>
			<td> {{ object.email }} </td>
		</tr>

		<tr>
			<th scope="row"> fecha de ingreso </th>
			<td> {{ object.fecha_de_ingreso }} </td>
		</tr>

		<tr>
			<th scope="row"> Observaciones </th>
			<td> {{ object.observaciones }} </td>
		</tr>

	</tbody>
</table>
<button type="button" class="btn btn-primary" onclick="window.history.back(); return false;">Volver</button>

{% endblock %}

funcionarios/templates/funcionario_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
{% endblock %}

{% block extrajs %}	
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Funcionarios</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>
							<th style="vertical-align:middle">
								<strong> Buscar:</strong>
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="Buscar.." name="q" value="{{ q }}">
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/funcionarios/funcionario" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			{% if perms.funcionarios.add_funcionario %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/funcionarios/funcionario/add/?next={{ request.path }}';" title="Agregar Funcionario">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}

			<!--
			<button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
				<i class="fa fa-file-excel-o"></i>
			</button>
			--> 
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Acciones</th>
				</tr>
			</thead>

			<tbody>
				{% for funcionario in object_list %}
				<tr>
					<td>{{ funcionario }}</td>
					<td>
						{% if perms.funcionarios.change_funcionario %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/funcionarios/funcionario/{{ funcionario.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.funcionarios.delete_funcionario %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/funcionarios/funcionario/{{ funcionario.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}


						<button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/funcionarios/funcionario/{{ funcionario.id }}/detail/';" title="Detalle">
							<i class="fa fa-list-ol"></i>
						</button>

						<!--
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/funcionarios/funcionario/{{ funcionario.id }}/print/';" title="Imprimir">
							<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
						</button>
						-->

					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/funcionarios/funcionario/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/funcionarios/funcionario/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/funcionarios/funcionario/?page={{ page }}&q={{ q }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/funcionarios/funcionario/?page={{ page_obj.next_page_number }}&q={{ q }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/funcionarios/funcionario/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}