clientes/urls.py
from django.conf.urls import patterns, include, url
from clientes.autocomplete import *
from clientes.views import *


urlpatterns = [
    url(
        'clienteautocomplete/$',
        ClienteAutocomplete.as_view(),
        name='cliente-autocomplete',
    ),

    url(r'^cliente/(?P<pk>\d+)/detail/$', ClienteDetailView.as_view(), name='cliente_det'),
    url(r'^cliente/$', ClienteListView.as_view(), name='cliente_lis'),
    url(r'^$', clientes_presentacion),
]

indusis/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
    url(r'^admin/clientes/', include('clientes.urls')),
    url(r'^admin/proveedores/', include('proveedores.urls')),
    url(r'^admin/funcionarios/', include('funcionarios.urls')),
    url(r'^admin/ingredientes/', include('ingredientes.urls')),
    url(r'^admin/recetas/', include('recetas.urls')),
    url(r'^admin/ordenes/', include('ordenes.urls')),


    url(r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Change admin site title
admin.site.site_header = "GRAFI EXPRESS"
admin.site.site_title = "Industria grafica"

clientes/models.py
# -*- coding: utf-8 -*-

from django.db import models

# Create your models here.
class Cliente(models.Model):
    razon_social = models.CharField(max_length=100, verbose_name="razón social")
    ruc = models.CharField(max_length=20, verbose_name="RUC", unique=True)
    direccion = models.CharField(max_length=200, null=True, blank=True, verbose_name="dirección")
    celular = models.CharField(max_length=50, null=True, blank=True)
    telefono = models.CharField(max_length=50, null=True, blank=True, verbose_name="teléfono")
    email = models.CharField(max_length=100, null=True, blank=True, verbose_name="e-mail")
    vendedor = models.ForeignKey('funcionarios.Funcionario', null=True, blank=True)

    def __unicode__(self):
        return unicode(self.razon_social)

clientes/forms.py
from dal import autocomplete
from django import forms
from clientes.models import *

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ('__all__')
        widgets = { 
        	"vendedor": autocomplete.ModelSelect2(url='funcionario-autocomplete'), 
        }

clientes/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from django.db.models import Q

from clientes.models import Cliente
from funcionarios.models import *
from extra.globals import *

# Create your views here.


class ClienteListView(ListView):
    model = Cliente
    template_name = "cliente_list.html"
    paginate_by = 30

    def get_queryset(self):
        clientes = Cliente.objects.all()
        q = self.request.GET.get('q', '')
        if q != '':
            clientes = clientes.filter( Q(nombre__icontains=q) | Q(ruc__startswith=q) | Q(razon_social__icontains=q) )

        vendedor_id=self.request.GET.get('vendedor_id','')
        if vendedor_id !='':
            clientes = clientes.filter(vendedor_id = vendedor_id)

        return clientes.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(ClienteListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        context['vendedores'] = Funcionario.objects.all()
        context['vendedor_id'] = int(self.request.GET.get('vendedor_id','')) if (self.request.GET.get('vendedor_id','') != '') else ''
        return context

    def render_to_response(self, context, **response_kwargs):
        if 'excel' in self.request.GET.get('excel', ''): 

            lista_datos=[]
            datos = self.get_queryset()
            for dato in datos:
                lista_datos.append([
                    dato.razon_social,
                    dato.ruc,
                    dato.direccion,
                    dato.telefono,
                    dato.celular,
                    dato.email,
                    dato.vendedor.get_full_name() if dato.vendedor != None else '',
                ])

            titulos=[ 'Razon social', 'RUC', 'Direccion', 'Telefono','Celular', 'Email', 'Vendedor']
            return listview_to_excel(lista_datos,'Clientes',titulos)
        
        return super(ClienteListView, self).render_to_response(context, **response_kwargs)

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(ClienteListView, self).dispatch(*args, **kwargs)

class ClienteDetailView(DetailView):
    model = Cliente
    template_name = "cliente_detail.html"


def clientes_presentacion(request):
    context = RequestContext(request)
    titulo="CLIENTES"
    descripcion=".."
    return render_to_response('admin/presentacion.html', {'titulo': titulo, 'descripcion': descripcion}, context)

clientes/templates/cliente_detail.html
{% extends "admin/base_site.html" %}

{% block content %}
<h1>Datos del Cliente</h1>
<table class="table table-striped table-filter" summary="Datos del Cliente.">
	<tbody>
		<tr>
			<th scope="row"> Razon Social </th>
			<td> {{ object }} </td>
		</tr>

		<tr>
			<th scope="row"> RUC </th>
			<td> {{ object.ruc }} </td>
		</tr>

		<tr>
			<th scope="row"> Direccion </th>
			<td> {{ object.direccion }} </td>
		</tr>

		<tr>
			<th scope="row"> Telefono </th>
			<td> {{ object.telefono }} </td>
		</tr>

		<tr>
			<th scope="row"> Celular </th>
			<td> {{ object.celular }} </td>
		</tr>

		<tr>
			<th scope="row"> E-mail </th>
			<td> {{ object.email }} </td>
		</tr>

		<tr>
			<th scope="row"> Vendedor </th>
			<td> {{ object.vendedor.get_full_name }}</td>
		</tr>

	</tbody>
</table>

<button type="button" class="btn btn-primary" onclick="window.history.back(); return false;">Volver</button>

{% endblock %}

clientes/templates/cliente_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>

    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
{% endblock %}

{% block content %}
	<h1>Lista de Clientes</h1>
	<form class="form" method="get">
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>
							<th style="vertical-align:middle">
								<strong> Cliente:</strong>
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="Razon social o RUC.." name="q" value="{{ q }}">
							</td>

							<th style="vertical-align:middle">
							    <strong> Vendedor:</strong>
							</th>
							<td style="vertical-align:middle">
							    <select class="chosen-select" data-placeholder="Seleccione un vendedor.." name="vendedor_id" value="{{ vendedor_id }}" onchange="this.form.submit();">
							        <option value=""></option>
							        {% for vendedor in vendedores %}
							            <option {% if vendedor.pk == vendedor_id %} selected {% endif %} value="{{ vendedor.id }}">{{ vendedor }}</option>
							        {% endfor %}
							    </select>
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/clientes/cliente" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			
			<button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
				<i class="fa fa-file-excel-o"></i>
			</button>
			
			{% if perms.clientes.add_cliente %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/clientes/cliente/add/';" title="Agregar Cliente">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}
			
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Razón Social</th>
					<th>RUC</th>
					<th>Telefono</th>
					<th>Email</th>
					<th>Vendedor</th>
					<th>Acciones</th>		 
				</tr>
			</thead>

			<tbody>
				{% for cliente in object_list %}
				<tr>
					<td>{{ cliente.razon_social }}</td>
					<td>{{ cliente.ruc }}</td>
					<td>{{ cliente.telefono }}</td>
					<td>{{ cliente.email }}</td>
					<td>{{ cliente.vendedor.get_full_name }}</td>

					<td>
						{% if perms.clientes.change_cliente %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/clientes/cliente/{{ cliente.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.clientes.delete_cliente %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/clientes/cliente/{{ cliente.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}


						<button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/clientes/cliente/{{ cliente.id }}/detail/';" title="Detalle">
							<i class="fa fa-list-ol"></i>
						</button>

						<!--
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/clientes/cliente/{{ cliente.id }}/print/';" title="Imprimir">
							<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
						</button>
						-->

					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/clientes/cliente/?page={{ page_obj.previous_page_number }}&q={{ q }}&vendedor_id={{ vendedor_id }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/clientes/cliente/?page={{ page_obj.previous_page_number }}&q={{ q }}&vendedor_id={{ vendedor_id }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/clientes/cliente/?page={{ page }}&q={{ q }}&vendedor_id={{ vendedor_id }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/clientes/cliente/?page={{ page_obj.next_page_number }}&q={{ q }}&vendedor_id={{ vendedor_id }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/clientes/cliente/?page={{ page_obj.paginator.num_pages}}&q={{ q }}&vendedor_id={{ vendedor_id }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}