indusis/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
    url(r'^admin/clientes/', include('clientes.urls')),
    url(r'^admin/proveedores/', include('proveedores.urls')),
    url(r'^admin/funcionarios/', include('funcionarios.urls')),
    url(r'^admin/ingredientes/', include('ingredientes.urls')),
    url(r'^admin/recetas/', include('recetas.urls')),
    url(r'^admin/ordenes/', include('ordenes.urls')),


    url(r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Change admin site title
admin.site.site_header = "GRAFI EXPRESS"
admin.site.site_title = "Industria grafica"

ingredientes/urls.py
from django.conf.urls import patterns, include, url
from ingredientes.autocomplete import *
from ingredientes.views import *
from ingredientes.ajax import *

urlpatterns = [
    url(
        'unidaddemedidaautocomplete/$',
        UnidadDeMedidaAutocomplete.as_view(),
        name='unidaddemedida-autocomplete',
    ),

    url(
        'categoriadeingredienteautocomplete/$',
        CategoriaDeIngredienteAutocomplete.as_view(),
        name='categoriadeingrediente-autocomplete',
    ),

    url(
        'ingredienteautocomplete/$',
        IngredienteAutocomplete.as_view(),
        name='ingrediente-autocomplete',
    ),

    url('getunidadesdemedidadelingrediente/$',get_unidades_de_medida_del_ingrediente),
    url('getpreciodelingrediente/$',get_precio_del_ingrediente),

    url(r'^unidaddemedida/$', UnidadDeMedidaListView.as_view(), name='unidaddemedida_lis'),

    url(r'^categoriadeingrediente/$', CategoriaDeIngredienteListView.as_view(), name='categoriadeingrediente_lis'),
    
    url(r'^ingrediente/$', IngredienteListView.as_view(), name='ingrediente_lis'),
    url(r'^ingrediente/(?P<pk>\d+)/detail/$', IngredienteDetailView.as_view(), name='ingrediente_det'),

    url(r'^$', ingredientes_presentacion),
]

ingredientes/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.apps import apps

class UnidadDeMedida(models.Model):
    class Meta:
        verbose_name = "unidad de medida"
        verbose_name_plural = "unidades de medida"

    nombre = models.CharField(max_length=100)
    abreviatura = models.CharField(max_length=10, verbose_name="Símbolo")

    def __str__(self):
        return self.nombre


class CategoriaDeIngrediente(models.Model):
    class Meta:
        verbose_name = "categoría de ingredientes"
        verbose_name_plural = "categorías de ingredientes"

    nombre = models.CharField(max_length=100, unique=True)
    nombre_completo = models.CharField(max_length=500, editable=False, null=True)
    categoria_padre = models.ForeignKey("self", related_name='categoria_fk', null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.categoria_padre != None:
            self.nombre_completo = self.categoria_padre.nombre_completo + " " + self.nombre
        else:
            self.nombre_completo = self.nombre

        super(CategoriaDeIngrediente, self).save(*args, **kwargs)

        categorias_hijas = CategoriaDeIngrediente.objects.filter(categoria_padre=self)
        for categoria_hija in categorias_hijas:
            categoria_hija.save()

    def __str__(self):
        return self.nombre_completo


IVA = (
    (10, 'IVA 10%'), 
    (5, 'IVA 5%'), 
    (0, 'EXENTA')
)
class Ingrediente(models.Model):
    class Meta:
        verbose_name_plural = "ingredientes"

    codigo = models.CharField(max_length=10, unique=True, verbose_name="código")
    descripcion = models.CharField(max_length=150, verbose_name="descripción")
    marca = models.CharField(max_length=100, null=True, blank=True)
    iva = models.IntegerField("IVA", choices=IVA, default=10)    
    categoria = models.ForeignKey(CategoriaDeIngrediente, verbose_name="categoría")
    proveedores = models.ManyToManyField('proveedores.Proveedor', blank=True)  
    precio_unitario = models.DecimalField(max_digits=15, decimal_places=2)
    stock_actual = models.DecimalField(max_digits=15, decimal_places=2, default=0, editable=False)

    def __unicode__(self):
        return unicode(self.descripcion + " - " + self.marca)

    def get_unidad_de_medida(self):
        return (TablaDeConversion.objects.filter(ingrediente_id = self.id)[0]).unidad_de_medida

    """
    def actualizar_stock(self):
        cantidad = 0

        detalles_altas = apps.get_model("depositos","DetalleAlta").objects.filter(ingrediente_id = self.id)
        for detalle in detalles_altas:
            cantidad = cantidad + detalle.cantidad

        detalles_bajas = apps.get_model("depositos","DetalleBaja").objects.filter(ingrediente_id = self.id)
        for detalle in detalles_bajas:
            cantidad = cantidad - detalle.cantidad

        detalles_retiros = apps.get_model("depositos","DetalleRetiro").objects.filter(ingrediente_id = self.id)
        for detalle in detalles_retiros:
            cantidad = cantidad - detalle.cantidad

        detalles_devoluciones = apps.get_model("depositos","DetalleDevolucion").objects.filter(detalle_retiro__ingrediente__id = self.id)
        for detalle in detalles_devoluciones:
            cantidad = cantidad + detalle.cantidad

        self.stock_actual = cantidad
        self.save()
    """


class TablaDeConversion(models.Model):
    class Meta:
        verbose_name = 'Otra unidad de medida'
        verbose_name_plural = 'Otras unidades de medida'

    ingrediente = models.ForeignKey(Ingrediente)
    unidad_de_medida = models.ForeignKey(UnidadDeMedida)
    factor_de_conversion = models.DecimalField(max_digits=15, decimal_places=2, help_text="Numero a multiplicar para convertir en la unidad de medida principal")

    def __unicode__(self):
        return self.unidad_de_medida.abreviatura 

ingredientes/forms.py
from dal import autocomplete
from django import forms
from ingredientes.models import *

class IngredienteForm(forms.ModelForm):
	class Meta:
		model = Ingrediente
		fields = ('__all__')
		widgets = { 
			"categoria": autocomplete.ModelSelect2(url='categoriadeingrediente-autocomplete'),
			"proveedores": autocomplete.ModelSelect2Multiple(url='proveedor-autocomplete'),
			"precio_unitario":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
		}

	unidad_de_medida = forms.ModelChoiceField(
		queryset=UnidadDeMedida.objects.all(),
		#widget=autocomplete.ModelSelect2(url='unidaddemedida-autocomplete'),
		required=True,
		label="Unidad de medida"
	)


	def __init__(self, *args, **kwargs):
		super(IngredienteForm, self).__init__(*args, **kwargs)
		instance = getattr(self, 'instance', None)
		if instance and instance.pk:
			self.initial['unidad_de_medida'] = instance.get_unidad_de_medida()


class TablaDeConversionForm(forms.ModelForm):
	class Meta:
		model = TablaDeConversion
		fields = ('__all__')
		widgets = {
			"factor_de_conversion":forms.TextInput(attrs={'style':'text-align:right','size':'12','class':'auto','data-a-sep':'.','data-a-dec':','}),
	   	}

	unidad_de_medida = forms.ModelChoiceField(
		queryset=UnidadDeMedida.objects.all(),
		#widget=autocomplete.ModelSelect2(url='unidaddemedida-autocomplete'),
		required=True,
		label="Unidad de medida"
	)

ingredientes/views.py
from django.shortcuts import render, render_to_response
from django.template.context import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from django.db.models import Q

from ingredientes.models import *
from extra.globals import *
# Create your views here.

class UnidadDeMedidaListView(ListView):
    model = UnidadDeMedida
    template_name = "unidaddemedida_list.html"
    paginate_by = 30

    def get_queryset(self):
        unidadesdemedidas = UnidadDeMedida.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            unidadesdemedidas = unidadesdemedidas.filter(nombre__icontains=q)

        return unidadesdemedidas

    def get_context_data(self, **kwargs):
        context = super(UnidadDeMedidaListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        return context



class CategoriaDeIngredienteListView(ListView):
    model = CategoriaDeIngrediente
    template_name = "categoriadeingrediente_list.html"
    paginate_by = 30

    def get_queryset(self):
        categoriasdeingredientes = CategoriaDeIngrediente.objects.all().order_by('nombre_completo')

        q = self.request.GET.get('q', '')
        if q != '':
            categoriasdeingredientes = categoriasdeingredientes.filter(Q(nombre_completo__icontains=q))
        return categoriasdeingredientes

    def get_context_data(self, **kwargs):
        context = super(CategoriaDeIngredienteListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        return context



class IngredienteListView(ListView):
    model = Ingrediente
    template_name = "ingrediente_list.html"
    paginate_by = 30

    def get_queryset(self):
        ingredientes = Ingrediente.objects.all()

        q = self.request.GET.get('q', '')
        if q != '':
            ingredientes = ingredientes.filter( Q(descripcion__icontains=q) | Q(id__startswith=q) )
        return ingredientes

    def get_context_data(self, **kwargs):
        context = super(IngredienteListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q','')
        return context

    def render_to_response(self, context, **response_kwargs):
        if 'excel' in self.request.GET.get('excel', ''): 

            lista_datos=[]
            datos = self.get_queryset()
            for dato in datos:
                lista_datos.append([
                    dato.codigo,
                    dato.descripcion,
                    dato.marca,
                    dato.get_iva_display(),
                    dato.categoria.nombre,
                    dato.stock_actual,
                    dato.get_unidad_de_medida().nombre,
                    separador_de_miles(dato.precio_unitario),
                ])

            titulos=[ 
                'Codigo',
                'Descripcion',  
                'Marca',
                'IVA',
                'Categoria', 
                'Stock actual',
                'Unidad de medida', 
                'Precio unitario', 
            ]
            return listview_to_excel(lista_datos,'Ingredientes',titulos)
        
        return super(IngredienteListView, self).render_to_response(context, **response_kwargs)

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(IngredienteListView, self).dispatch(*args, **kwargs)

class IngredienteDetailView(DetailView):
    model = Ingrediente
    template_name = "ingrediente_detail.html"

    def get_context_data(self, **kwargs):
        context = super(IngredienteDetailView, self).get_context_data(**kwargs)
        return context

def ingredientes_presentacion(request):
    context = RequestContext(request)
    titulo="INGREDIENTES"
    descripcion=".."
    return render_to_response('admin/presentacion.html', {'titulo': titulo, 'descripcion': descripcion}, context)

ingredientes/templates/categoriadeingrediente_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
{% endblock %}

{% block extrajs %}	
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Categorias</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>
							<th style="vertical-align:middle">
								<strong> Buscar:</strong>
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="Nombre.." name="q" value="{{ q }}">
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/ingredientes/categoriadeingrediente" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			{% if perms.ingredientes.add_categoriadeingrediente %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/ingredientes/categoriadeingrediente/add/';" title="Agregar Categoria">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}

			<!--
			<button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
				<i class="fa fa-file-excel-o"></i>
			</button>
			--> 
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Acciones</th>
				</tr>
			</thead>

			<tbody>
				{% for categoriadeingrediente in object_list %}
				<tr>
					<td>{{ categoriadeingrediente.nombre_completo }}</td>

					<td>
						{% if perms.ingredientes.change_categoriadeingrediente %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/ingredientes/categoriadeingrediente/{{ categoriadeingrediente.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.ingredientes.delete_categoriadeingrediente %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/ingredientes/categoriadeingrediente/{{ categoriadeingrediente.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}

						<!--
						<button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/ingredientes/categoriadeingrediente/{{ categoriadeingrediente.id }}/detail/';" title="Detalle">
							<i class="fa fa-list-ol"></i>
						</button>


						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/ingredientes/categoriadeingrediente/{{ categoriadeingrediente.id }}/print/';" title="Imprimir">
							<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
						</button>
						-->

					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/ingredientes/categoriadeingrediente/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/ingredientes/categoriadeingrediente/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/ingredientes/categoriadeingrediente/?page={{ page }}&q={{ q }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/ingredientes/categoriadeingrediente/?page={{ page_obj.next_page_number }}&q={{ q }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/ingredientes/categoriadeingrediente/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}

ingredientes/templates/ingrediente_detail.html
{% extends "admin/base_site.html" %}
{% load humanize %}

{% block content %}
<h1>Datos del Ingrediente</h1>
<table class="table table-striped table-filter" summary="Datos del Ingrediente.">
	<tbody>
		<tr>
			<th scope="row"> Codigo </th>
			<td> {{ object.id }} </td>
		</tr>

		<tr>
			<th scope="row"> Descripcion </th>
			<td> {{ object.descripcion }} </td>
		</tr>

		<tr>
			<th scope="row"> Marca </th>
			<td> {{ object.marca }} </td>
		</tr>

		<tr>
			<th scope="row"> Unidad de Medida </th>
			<td> {{ object.get_unidad_de_medida }} </td>
		</tr>

		<tr>
			<th scope="row"> Categoria </th>
			<td> {{ object.categoria }} </td>
		</tr>

		<tr>
			<th scope="row"> Stock Actual </th>
			<td> {{ object.stock_actual|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }} </td>
		</tr>

		<tr>
			<th scope="row"> Precio unitario </th>
            <td>{{ ingrediente.precio_unitario|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
		</tr>

	</tbody>
</table>

{% if object.proveedores.all %}
<table id="result_list" class="table table-striped table-bordered table-hover table-condensed">
	<caption><h1>Proveedores</h1></caption>

	<thead>
		<tr>
			<th>Nombre</th>
		</tr>
	</thead>

	<tbody>
		{% for proveedor in object.proveedores.all %}
		<tr>
			<td>{{ proveedor }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endif %}

<button type="button" class="btn btn-primary" onclick="window.history.back(); return false;">Volver</button>

{% endblock %}

ingredientes/templates/ingrediente_list.html
{% extends 'admin/base_site.html' %}
{% load humanize %}

{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
{% endblock %}

{% block extrajs %}
{% endblock %}

{% block content %}
    <form class="form" method="get">
        <h1>Lista de Ingredientes</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Buscar:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text" class="search-query" placeholder="Nombre o codigo.." name="q" value="{{ q }}">
                        </td>

                        <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                            <a class="btn btn-info" href="/admin/ingredientes/ingrediente" title="Limpiar Filtros">
                                <i class="fa fa-undo"></i>
                            </a>
                            <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                        </th>
                    </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">

            <button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
                <i class="fa fa-file-excel-o"></i>
            </button>

            {% if perms.ingredientes.add_ingrediente %}
                <button type="button" class="btn btn-primary" onclick="location.href='/admin/ingredientes/ingrediente/add/';" title="Agregar Ingrediente">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            {% endif %}

        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>
                <th>Codigo</th>
                <th>Ingrediente</th>
                <th>Categoria</th>
                <th>Stock actual</th>
                <th>Precio unitario</th>
                <th>Acciones</th>

            </tr>
            </thead>

            <tbody>
            {% for ingrediente in object_list %}
                <tr>
                    <td>{{ ingrediente.codigo }}</td>
                    <td>{{ ingrediente.descripcion}}</td>
                    <td>{{ ingrediente.categoria }}</td>
                    <td>{{ ingrediente.stock_actual|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>
                    <td>{{ ingrediente.precio_unitario|floatformat:"0"|intcomma|default_if_none:"&nbsp;" }}</td>

                    <td>
                        {% if perms.ingredientes.change_ingrediente %}
                            <button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/ingredientes/ingrediente/{{ ingrediente.id }}/';" title="Editar">
                                <i class="fa fa-pencil"></i>
                            </button>
                        {% endif %}

                        {% if perms.ingredientes.delete_ingrediente %}
                            <button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/ingredientes/ingrediente/{{ ingrediente.id }}/delete/';" title="Borrar">
                                <i class="fa fa-minus"></i>
                            </button>
                        {% endif %}


                        <button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/ingredientes/ingrediente/{{ ingrediente.id }}/detail/';" title="Detalle">
                            <i class="fa fa-list-ol"></i>
                        </button>

                        <!--
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/ingredientes/ingrediente/{{ ingrediente.id }}/print/';" title="Imprimir">
							<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
						</button>
						-->

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/ingredientes/ingrediente/?page={{ page_obj.previous_page_number }}&q={{ q }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/ingredientes/ingrediente/?page={{ page_obj.previous_page_number }}&q={{ q }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/ingredientes/ingrediente/?page={{ page }}&q={{ q }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/ingredientes/ingrediente/?page={{ page_obj.next_page_number }}&q={{ q }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/ingredientes/ingrediente/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}

ingredientes/templates/unidaddemedida_list.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
{% endblock %}

{% block extrajs %}	
{% endblock %}

{% block content %}
	<form class="form" method="get">
		<h1>Lista de Unidades de Medida</h1>
		<center>
			<dl>
				<table class="table-filter table table-bordered table-stripped">
					<tbody>
						<tr>
							<th style="vertical-align:middle">
								<strong> Buscar:</strong>
							</th>
							<td style="vertical-align:middle">
								<input type="text" class="search-query" placeholder="Nombre.." name="q" value="{{ q }}">
							</td>

							<th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
								<a class="btn btn-info" href="/admin/ingredientes/unidaddemedida/" title="Limpiar Filtros">
									<i class="fa fa-undo"></i>
								</a>
								<input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
							</th>
						</tr>
					</tbody>
				</table>
			</dl>
		</center>
		
		<div id="next_button" align="right">
			{% if perms.ingredientes.add_unidaddemedida %}
			<button type="button" class="btn btn-primary" onclick="location.href='/admin/ingredientes/unidaddemedida/add/';" title="Agregar Unidad de Medida">
				<span class="glyphicon glyphicon-plus"></span>
			</button>
			{% endif %}

			<!--
			<button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
				<i class="fa fa-file-excel-o"></i>
			</button>
			--> 
		</div>
	</form>


	<br/>

	<div align="center">
		<table id="result_list" class="table table-striped table-filter">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Abreviatura</th>
					<th>Acciones</th>
				</tr>
			</thead>

			<tbody>
				{% for unidaddemedida in object_list %}
				<tr>
					<td>{{ unidaddemedida.nombre }}</td>
					<td>{{ unidaddemedida.abreviatura }}</td>
					<td>
						{% if perms.ingredientes.change_unidaddemedida %}
						<button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/ingredientes/unidaddemedida/{{ unidaddemedida.id }}/';" title="Editar">
							<i class="fa fa-pencil"></i>
						</button>
						{% endif %}

						{% if perms.ingredientes.delete_unidaddemedida %}
						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/ingredientes/unidaddemedida/{{ unidaddemedida.id }}/delete/';" title="Borrar">
							<i class="fa fa-minus"></i>
						</button>
						{% endif %}

						<!--
						<button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/ingredientes/unidaddemedida/{{ unidaddemedida.id }}/detail/';" title="Detalle">
							<i class="fa fa-list-ol"></i>
						</button>


						<button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/ingredientes/unidaddemedida/{{ unidaddemedida.id }}/print/';" title="Imprimir">
							<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
						</button>
						-->

					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% if is_paginated %}
	<table class="table">
		<td>
			<center>
				<ul class="pagination pagination-sm">
					{% if page_obj.has_previous %}
					<li class="previous">
						<a href="/admin/ingredientes/unidaddemedida/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							<span aria-hidden="true">&larr;</span> Primera
						</a>
					</li>

					<li>
						<a href="/admin/ingredientes/unidaddemedida/?page={{ page_obj.previous_page_number }}&q={{ q }}">
							Anterior
						</a>
					</li> 	
					{% endif %}

					{% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
					<li>
						<a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/ingredientes/unidaddemedida/?page={{ page }}&q={{ q }}">
							{{ page }}
						</a>
					</li>
					{% endfor %}

					{% if page_obj.has_next %}
					<li>
						<a href="/admin/ingredientes/unidaddemedida/?page={{ page_obj.next_page_number }}&q={{ q }}">
							Siguiente
						</a>
					</li>
					
					<li class="next">
						<a href="/admin/ingredientes/unidaddemedida/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
							&Uacute;ltima <span aria-hidden="true">&rarr;</span>
						</a>
					</li>
					{% endif %}

				</ul>
			</center>
		</td>
		<th>
			Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} 
		</th>
	</table>
	{% endif %}
{% endblock %}